#!/usr/bin/env bash
#
# bootstrap.sh — first-boot setup for a Churner environment host (design spec
# §7). Run once, by the host's own UserData.
#
# Fetched and run by the environment host's UserData, which is the ONLY thing
# the rendered CloudFormation / Terraform body carries: the stack passes the
# module's coordinates in the environment and hands over to this file, so the
# copy a customer reviews in the repository is byte-for-byte the copy the host
# runs. Inlining a few hundred lines of shell into a template would make those
# two different files.
#
# ## The integrity chain
#
# UserData fetches this file from a PINNED tag and verifies it against the
# `EnvironmentBootstrapSha256` stack parameter (mirrored here as
# `ENVIRONMENT_BOOTSTRAP_SHA256` in `shared/access/environment-stack.ts`)
# BEFORE running it. Everything this file goes on to fetch — the Caddyfile
# template and the Caddy release tarball — is verified against the digest
# table below. The chain therefore has exactly one root of trust (a digest the
# customer can read in their own stack parameters) and no unverified hop:
# without it, a bad commit on a moving branch would execute as root on every
# environment host that booted after it.
#
# The table is generated by `scripts/environment-stack-digests.sh` and
# asserted against the repository by a test in
# `shared/tests/environment-stack.test.ts`, so editing one of those files
# without regenerating the table fails CI rather than failing at 3am on a
# customer's host.
#
# What it installs:
#   - Docker (the release container) and the SSM agent (already present on
#     AL2023, enabled here so a fresh AMI cannot arrive without it);
#   - Caddy, as a reverse proxy fronting the release. With a domain configured
#     it obtains and renews its own ACME certificate — there is no load
#     balancer in front of an environment host for the challenge to reach
#     instead. Without one, it answers plain HTTP on :80;
#   - `$CHURNER_ROUTES_DIR`, the directory the release workflow's host script
#     (`deploy-release.sh`) drops one route file into per release;
#   - the CloudWatch agent, so the release container's logs reach
#     `$CHURNER_LOG_GROUP`;
#   - the Postgres client and `python3`, which the stack's own
#     `Custom::ChurnerDbRoles` command runs ON THIS HOST to create Churner's
#     database login (`DB_ROLES_HOST_PACKAGES`, see the Packages section).
#
# Written for bash 3.2 (no associative arrays, no `mapfile`, no `${x^^}`) so
# `bash -n` on a developer's macOS is the same check CI runs — the same rule
# `deploy-preview.sh` states in its own header.
#
# Idempotent: re-running it re-installs the units and rewrites the config,
# which is what a re-bootstrap after an AMI change should do.

set -euo pipefail

log() { echo "[churner-environment-bootstrap] $*"; }
die() { echo "[churner-environment-bootstrap] $*" >&2; exit 1; }

# --- Pinned artefact digests ------------------------------------------------
#
# Regenerate the SHA256_ lines with `scripts/environment-stack-digests.sh`.
#
# The Caddy tarball is pinned by SHA-512 because that is what the Caddy
# project publishes in its release `checksums.txt` — a digest upstream vouches
# for is better provenance than one we computed by downloading the same bytes
# once. The two values below are copied verbatim from:
#
#   https://github.com/caddyserver/caddy/releases/download/v2.11.4/caddy_2.11.4_checksums.txt
#
# CADDY_VERSION and those two digests move TOGETHER, always: a version bumped
# without re-pinning fails `verify_sha512` on every host, which is the
# intended failure — the alternative is a host silently running a build
# nobody checked.
CADDY_VERSION="2.11.4"
#
# BEGIN CHURNER ENVIRONMENT DIGESTS
SHA256_CADDYFILE_TMPL="056eef2aae377707dd673c64bfd4bf1fa1b9a77150169d97f388ebed50a5b31b"
SHA512_CADDY_LINUX_ARM64="d5a7c423853c24a799765e0e8210d5c7c22a8f56ed37a3cae2fb9f58be138853c02b4efd6b59d576e6d8c7c0d30b9c1592deeaa6a536ff69bcca23b8c1ea709c"
SHA512_CADDY_LINUX_AMD64="8220d1f013b6f27510247b2360c9e0ca9f018feebd82515f07635318b34ff9777ccc8fd0b6e6f2486ce3a33fe389fbb7db12d05baa474f4587509fb4f5ebf1c9"
# END CHURNER ENVIRONMENT DIGESTS

verify_sha256() {
  # verify_sha256 <file> <expected-sha256>
  if ! printf '%s  %s\n' "$2" "$1" | sha256sum -c - >/dev/null 2>&1; then
    die "checksum mismatch for $1 (expected sha256 $2) — refusing to continue"
  fi
}

verify_sha512() {
  # verify_sha512 <file> <expected-sha512>
  actual="$(sha512sum "$1" | cut -d' ' -f1)"
  if [ "$actual" != "$2" ]; then
    die "checksum mismatch for $1 (expected sha512 $2, got $actual) — refusing to continue"
  fi
}

fetch_verified() {
  # fetch_verified <url-path> <destination> <expected-sha256>
  curl -fsSL "${SCRIPTS_BASE_URL}/$1" -o "$2"
  verify_sha256 "$2" "$3"
}

# --- Inputs -----------------------------------------------------------------
#
# Every one of these is written by the stack's UserData. They are re-checked
# here rather than assumed: a host that boots with an empty secrets prefix
# would read no application secrets, and the failure would look like a broken
# application instead of a missing input.

SCRIPTS_BASE_URL="${CHURNER_SCRIPTS_BASE_URL:-}"
PROJECT_KEY="${CHURNER_PROJECT_KEY:-}"
ENVIRONMENT="${CHURNER_ENVIRONMENT:-}"
SECRETS_PREFIX="${CHURNER_SECRETS_PREFIX:-}"
LOG_GROUP="${CHURNER_LOG_GROUP:-}"
ENVIRONMENT_DOMAIN="${CHURNER_ENVIRONMENT_DOMAIN:-}"
AWS_REGION_NAME="${CHURNER_AWS_REGION:-}"
HEALTH_PATH="${CHURNER_HEALTH_PATH:-/}"
ROUTES_DIR="${CHURNER_ROUTES_DIR:-/etc/caddy/release-routes}"
CONFIG_DIR=/etc/churner-environment

# CloudFormation resource signalling. Empty under Terraform, which has no
# equivalent — there the host reports readiness by registering with SSM.
CFN_STACK="${CHURNER_CFN_STACK:-}"
CFN_RESOURCE="${CHURNER_CFN_RESOURCE:-}"

# --- CloudFormation signal --------------------------------------------------
#
# Installed BEFORE the first thing that can fail, so a stack whose host cannot
# bootstrap fails in minutes with the reason in the console rather than
# reporting CREATE_COMPLETE on a host serving nothing.

CFN_SIGNAL_SENT=0
signal_cfn() {
  [ -n "$CFN_STACK" ] || return 0
  [ "$CFN_SIGNAL_SENT" = "0" ] || return 0
  CFN_SIGNAL_SENT=1
  cfn_bin=/opt/aws/bin/cfn-signal
  [ -x "$cfn_bin" ] || cfn_bin="$(command -v cfn-signal || true)"
  if [ -z "$cfn_bin" ]; then
    echo "[churner-environment-bootstrap] cfn-signal is not installed; cannot report status $1" >&2
    return 0
  fi
  "$cfn_bin" --exit-code "$1" \
    --stack "$CFN_STACK" \
    --resource "$CFN_RESOURCE" \
    --region "$AWS_REGION_NAME" || true
}
trap 'rc=$?; signal_cfn "$rc"' EXIT

[ -n "$SCRIPTS_BASE_URL" ] || die "CHURNER_SCRIPTS_BASE_URL is required"
[ -n "$PROJECT_KEY" ] || die "CHURNER_PROJECT_KEY is required"
[ -n "$ENVIRONMENT" ] || die "CHURNER_ENVIRONMENT is required"
[ -n "$SECRETS_PREFIX" ] || die "CHURNER_SECRETS_PREFIX is required"

# Everything fetched from here is digest-verified below, so plain HTTP would
# not let an interloper change what runs — but it WOULD let one see it, and a
# stack whose script base is `http://` is a misconfiguration worth refusing at
# the first opportunity rather than serving from. The release workflow makes
# the same check on its own copy of this value.
case "$SCRIPTS_BASE_URL" in
  https://*) ;;
  *) die "CHURNER_SCRIPTS_BASE_URL must be https (got '${SCRIPTS_BASE_URL}')" ;;
esac

# `SITE` and `ROUTES_DIR` are substituted into the proxy's own configuration
# below, and `ROUTES_DIR` is a path this script creates. A `#` would break the
# `sed` expression's delimiter; a `{`, a `}` or a newline would close or open a
# Caddy block that nobody wrote. Both values come from the stack the customer
# applied — checked anyway, because the failure mode is a proxy configuration
# nobody authored, on the host that answers their users.
#
# `grep -Eqx` against a value first proved to be a SINGLE LINE: `grep -Eq
# '^…$'` succeeds when ANY LINE matches, so a domain of `example.com` followed
# by a newline and `{ evil }` passed the hostname check below (fix-round-1
# review, N7) — and the `sed` further down would then have written both lines
# into the proxy's configuration.
one_line_matches() {
  # one_line_matches <value> <extended-regex>
  [ "$(printf '%s' "$1" | wc -l | tr -d '[:space:]')" = "0" ] || return 1
  printf '%s' "$1" | grep -Eqx "$2"
}

if [ -n "$ENVIRONMENT_DOMAIN" ]; then
  one_line_matches "$ENVIRONMENT_DOMAIN" '[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?' \
    || die "CHURNER_ENVIRONMENT_DOMAIN is not a hostname (got '${ENVIRONMENT_DOMAIN}')"
fi
one_line_matches "$ROUTES_DIR" '/[A-Za-z0-9._/-]+' \
  || die "CHURNER_ROUTES_DIR is not a usable directory path (got '${ROUTES_DIR}')"
one_line_matches "$HEALTH_PATH" '/[A-Za-z0-9._~/-]*' \
  || die "CHURNER_HEALTH_PATH must be a rooted path (got '${HEALTH_PATH}')"

log "bootstrapping ${ENVIRONMENT} environment host for ${PROJECT_KEY}"

# --- Packages ---------------------------------------------------------------
#
# Output is NOT redirected: when this fails it is the only line that says why,
# and it reaches the console log through cloud-init.

log "installing packages"
dnf install -y docker tar gzip jq awscli-2 aws-cfn-bootstrap amazon-cloudwatch-agent

# The database-login packages, on a line of their own because the client has
# two possible names and a whole-list retry would reinstall the six above to
# find that out.
#
# THIS HOST is where the stack's `Custom::ChurnerDbRoles` command runs — the
# environment owns its database and its host role already holds a permanent
# read of the master secret, so the roles command targets it rather than the
# project's reach instance. That command runs `psql` and parses the secret
# with `python3`. Until 2026-09-18 neither was installed here, and both roles
# resources failed with `psql: command not found` — rolling back an apply
# that had already built two databases and two hosts.
#
# The list is DECLARED ONCE, in `shared/access/db-roles-host.ts`
# (`DB_ROLES_HOST_PACKAGES`), which the reach instance's bootstrap renders
# from and which a test in `shared/tests/environment-stack.test.ts` asserts
# against these two lines verbatim — a shell file cannot import, so the test
# is what keeps the two copies from drifting.
#
# `set -e` is on, so both names failing stops the script here and the EXIT
# trap signals CloudFormation with the failure. That is the loud posture the
# reach bootstrap takes for the same packages: a host that comes up without
# `psql` fails later, somewhere else, about something else.
dnf install -y postgresql16 python3 ||
  dnf install -y postgresql15 python3

systemctl enable --now docker
systemctl enable --now amazon-ssm-agent

# --- Caddy ------------------------------------------------------------------
#
# Installed from the upstream release tarball rather than a distribution
# package: AL2023 carries no Caddy, and the alternative (enabling a Fedora
# COPR on Amazon Linux) is a repository the customer did not choose.

ARCH="$(uname -m)"
case "$ARCH" in
  aarch64|arm64) CADDY_ARCH=arm64; CADDY_SHA512="$SHA512_CADDY_LINUX_ARM64" ;;
  x86_64|amd64)  CADDY_ARCH=amd64; CADDY_SHA512="$SHA512_CADDY_LINUX_AMD64" ;;
  *) die "unsupported architecture: $ARCH" ;;
esac

if ! command -v caddy >/dev/null 2>&1; then
  log "installing caddy ${CADDY_VERSION} (${CADDY_ARCH})"
  CADDY_TMP="$(mktemp -d)"
  curl -fsSL \
    "https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_${CADDY_ARCH}.tar.gz" \
    -o "${CADDY_TMP}/caddy.tar.gz"
  verify_sha512 "${CADDY_TMP}/caddy.tar.gz" "$CADDY_SHA512"
  tar -xzf "${CADDY_TMP}/caddy.tar.gz" -C "$CADDY_TMP" caddy
  install -m 0755 "${CADDY_TMP}/caddy" /usr/local/bin/caddy
  rm -rf "$CADDY_TMP"
fi

id caddy >/dev/null 2>&1 || useradd --system --home /var/lib/caddy --shell /usr/sbin/nologin caddy
install -d -m 0755 /etc/caddy
install -d -m 0755 "$ROUTES_DIR"
install -d -o caddy -g caddy -m 0750 /var/lib/caddy

# The Caddyfile ends with `import <routes>/*.caddy`, and some Caddy versions
# treat a glob matching zero files as a configuration error — which would mean
# a host with no release deployed yet refuses to start, i.e. every host on its
# first boot. A comment-only placeholder makes the empty case identical to the
# busy one. `deploy-release.sh` writes over the live route file, never this
# one.
cat > "${ROUTES_DIR}/00-placeholder.caddy" <<'PLACEHOLDER'
# Placeholder so the route glob always matches. The release route is written
# beside this file by deploy-release.sh.
PLACEHOLDER

log "writing the Caddyfile"
fetch_verified proxy/Caddyfile.tmpl /etc/caddy/Caddyfile.tmpl "$SHA256_CADDYFILE_TMPL"
SITE=":80"
[ -n "$ENVIRONMENT_DOMAIN" ] && SITE="$ENVIRONMENT_DOMAIN"
# Both substituted values were checked against an explicit shape in the
# validation block above, so neither can carry the `#` that delimits these
# expressions, a newline, or a brace that would open or close a Caddy block.
# The check is the escaping: there is no quoting of a Caddyfile value that
# would make an arbitrary string safe here, only a refusal to render one.
sed -e "s#@@ROUTES_DIR@@#${ROUTES_DIR}#g" -e "s#@@SITE@@#${SITE}#g" \
  /etc/caddy/Caddyfile.tmpl > /etc/caddy/Caddyfile
# The rendered file is what the unit runs; a template placeholder left behind
# would be a site address of `@@SITE@@`, which Caddy accepts as a hostname and
# nothing ever reaches.
if grep -q '@@' /etc/caddy/Caddyfile; then
  die "the rendered Caddyfile still carries a template placeholder"
fi

cat > /etc/systemd/system/caddy.service <<'UNIT'
[Unit]
Description=Caddy reverse proxy for a Churner environment
After=network-online.target
Wants=network-online.target

[Service]
User=caddy
Group=caddy
ExecStart=/usr/local/bin/caddy run --environ --config /etc/caddy/Caddyfile
# SIGUSR1, not `caddy reload`: the Caddyfile sets `admin off`, so the reload
# subcommand — which POSTs to the admin API — has nothing to talk to and every
# route add/remove would be a silent no-op. `caddy run` re-reads its config on
# SIGUSR1 with no admin endpoint at all.
#
# SIGUSR1 config reload landed in Caddy 2.11.0. On an older build the signal
# is not handled and the reload is the same silent no-op by a different
# route — which is why CADDY_VERSION above is 2.11.x and a test asserts it.
ExecReload=/bin/kill -USR1 $MAINPID
Restart=on-failure
RestartSec=5s
# Ports 80/443 are below 1024 and Caddy runs unprivileged.
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
UNIT

# --- CloudWatch agent --------------------------------------------------------
#
# Points the release container's own log stream (docker's json-file log
# driver, read from disk — no `awslogs` driver, which would need every
# container the host ever runs to be started with the right log options) at
# this environment's log group.

install -d -m 0755 /opt/aws/amazon-cloudwatch-agent/etc
cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json <<CWCONFIG
{
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/lib/docker/containers/*/*.log",
            "log_group_name": "${LOG_GROUP}",
            "log_stream_name": "{instance_id}",
            "timezone": "UTC"
          }
        ]
      }
    }
  }
}
CWCONFIG
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
  -a fetch-config -m ec2 -s \
  -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json \
  || log "cloudwatch agent config failed to apply; continuing without shipped logs"

# --- Shared configuration ---------------------------------------------------
#
# One file every later process reads, so `deploy-release.sh` knows where
# things are without re-deriving them. It carries the host's TOPOLOGY, which
# is fixed at first boot; everything that belongs to one RELEASE — the image,
# the tag, the database secret's ARN, the application secret names, the health
# path — arrives in the SSM command body instead, and wins over anything of
# the same name here. A value fixed at first boot cannot be corrected without
# replacing the host.

install -d -m 0755 "$CONFIG_DIR"
cat > "${CONFIG_DIR}/env" <<CONFIG
CHURNER_PROJECT_KEY=${PROJECT_KEY}
CHURNER_ENVIRONMENT=${ENVIRONMENT}
CHURNER_SECRETS_PREFIX=${SECRETS_PREFIX}
CHURNER_LOG_GROUP=${LOG_GROUP}
CHURNER_AWS_REGION=${AWS_REGION_NAME}
CHURNER_ROUTES_DIR=${ROUTES_DIR}
CHURNER_HEALTH_PATH=${HEALTH_PATH}
CONFIG
# The file names secrets; it does not contain them. Still 0640 — nothing
# outside root has any business reading the host's topology.
chmod 0640 "${CONFIG_DIR}/env"

systemctl daemon-reload
systemctl enable --now caddy

log "done — the environment host is ready for its first release"
